#define SECRET_WIFI_SSID "INSERISCI_QUI_IL_NOME_WIFI"
#define SECRET_WIFI_PASS "INSERISCI_QUI_LA_PASSWORD"

#define SECRET_FIREBASE_API_KEY "INSERISCI_API_KEY"
#define SECRET_FIREBASE_URL "INSERISCI_URL_DATABASE"
#define SECRET_USER_EMAIL "INSERISCI_EMAIL_UTENTE"
#define SECRET_USER_PASS "INSERISCI_PASSWORD_UTENTE"

#define SECRET_OTA_USER "admin"
#define SECRET_OTA_PASS "password_per_ota"
